version: '2'
services:
  tomcat:
    container_name: firefly-worker
    volumes:
      - ./var/log/tomcat:/opt/tomcat/logs
    expose:
      - "8009"
    image: bshp/firefly-tomcat:latest
    build:
      context: .
      dockerfile: opt/tomcat/Dockerfile
      args:
        - JAVA_HOME=/opt/java-11-openjdk #java-8-openjdk or java-11-openjdk
        - TOMCAT_VERSION=9.0.36
  httpd:
    container_name: firefly-frontend
    volumes:
      - ./var/log/apache2:/var/log/apache2
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    image: bshp/firefly-httpd:latest
    build:
      context: .
      dockerfile: opt/httpd/Dockerfile
